Add db-update command to run update of database, entities and config

diff --git a/php/7.3/node/11/scripts/docker-as-drupal b/php/7.3/node/11/scripts/docker-as-drupal
--- a/php/7.3/node/11/scripts/docker-as-drupal
+++ b/php/7.3/node/11/scripts/docker-as-drupal
@@ -22,6 +22,7 @@ set -e
 : ${SYMFONY_DEPRECATIONS_HELPER:="weak"}
 : ${TEST_SERVER_PORT:="8888"}
 : ${CONFIG_IMPORT_ATTEMPTS:="5"}
+: ${DISABLE_DEVELOPMENT:=0}
 
 # Script variables
 BEHAT_OUTPUT_DIRECTORY="${LOG_DIR}/behat"
@@ -31,7 +32,6 @@ DATABASE_NAME=${DATABASE_URL##*/}
 DATABASE_USER=$(a=${DATABASE_URL#*//}; echo ${a%:*})
 DEFAULT_CONTENT_MODULES=""
 DRUPAL_IS_INSTALLED=0
-DEVELOPMENT=1
 RELATIVE_SITE_CONFIG_DIR=$(realpath --relative-to=/var/www/web ${SITE_CONFIG_DIR})
 SCRIPT_NAME=$(basename $0)
 TEST_SERVER_HOST="0.0.0.0"
@@ -77,6 +77,10 @@ function print_help() {
     Restore database from dump created with db-dump.
 
     --file=<path>            # Path to dump file (not required)
+
+  * db-update
+
+    Update database, entities and import config.
 
   * php-server
 
@@ -230,7 +234,7 @@ function yarn_is_installed() {
 
 # Return TRUE if development mode is enbale (default)
 function is_development() {
-  [ $DEVELOPMENT -eq 1 ]
+  [ $DISABLE_DEVELOPMENT -ne 0 ]
 }
 
 # Install dependencies
@@ -266,15 +270,8 @@ function database_reset() {
   # Load database dump to reset its state
   $(drush sql:connect) < $FILE_PATH
 
-  # First attemps to update database (can fail)
-  drush updatedb -y || true
-
   # Load Drupal config
   import_drupal_config
-
-  # Final attempt to update database and entities
-  drush updatedb -y
-  drush entity:update -y
 
   # Set Drupal install env to TRUE
   DRUPAL_IS_INSTALLED=1
@@ -295,8 +292,14 @@ function database_dump() {
 # Sometimes Drupal import configs in wrong orders.
 # So we repeat the config-import max. 4 times on successives fails.
 function import_drupal_config() {
-  printf "\e[1;35m* Import drupal configuration.\e[0m\n"
+  # Rebuild cache
+  drush cache-rebuild
 
+  # First attemps to update database (may fail)
+  printf "\e[1;35m* Update database (may fail).\e[0m\n"
+  drush updatedb -y || true
+
+  printf "\e[1;35m* Import drupal configuration.\e[0m\n"
   (
     set +e
 
@@ -322,6 +325,11 @@ function import_drupal_config() {
   # Fix Sitename bugged keep display "| Drupal"
   # @see https://www.drupal.org/node/2851877
   drush -q ev '\Drupal::languageManager()->getLanguageConfigOverrideStorage("fr")->delete("system.site");' >/dev/null 2>&1 || true
+
+  # Final attempt to update database and entities
+  printf "\e[1;35m* Update database and entities.\e[0m\n"
+  drush updatedb -y
+  drush entity:update -y
 
   # Rebuild cache
   drush cache-rebuild
@@ -425,15 +433,8 @@ if [ "$1" = "bootstrap" ]; then
       drush config-set system.site uuid "$SITE_UUID" -y
     )
 
-    # First attemps to update database (can fail)
-    drush updatedb -y || true
-
     # Load config
     import_drupal_config
-
-    # Final attempt to update database and entities
-    drush updatedb -y
-    drush entity:update -y
 
     # Save database dump after install
     database_dump
@@ -594,6 +595,18 @@ elif [ "$1" = "db-restore" ]; then
 
   # Reset database without default content
   database_reset "$FILE_PATH"
+
+#
+# UPDATE DATABASE
+#
+elif [ "$1" = "db-update" ]; then
+  shift
+
+  # Setup settings & Co.
+  setup
+
+  # Load config
+  import_drupal_config
 
 #
 # RUN PHP SERVER
