update Dockerfile for all versions

diff --git a/php/7.3/node/10/scripts/docker-as-drupal b/php/7.3/node/10/scripts/docker-as-drupal
--- a/php/7.3/node/10/scripts/docker-as-drupal
+++ b/php/7.3/node/10/scripts/docker-as-drupal
@@ -167,6 +167,11 @@ function setup() {
     echo '$databases["default"]["default"] = \Drupal\Core\Database\Database::convertDbUrlToConnectionInfo(getenv("DATABASE_URL"), DRUPAL_ROOT);' >> ./web/sites/default/settings.php
   fi
 
+  # Disabling "automated cron"
+  if ! grep -Eq "\\\$config\['automated_cron.settings'\]\['interval'\]" ./web/sites/default/settings.php; then
+    echo "\$config['automated_cron.settings']['interval'] = '0';" >> ./web/sites/default/settings.php
+  fi
+
   # Setup mailer
   printf "\e[1;35m* Setup mail host.\e[0m\n"
   if ! grep -Eq "\\\$config\['swiftmailer.transport'\]\['(smtp_host|smtp_port|smtp_encryption)'\]" ./web/sites/default/settings.php; then
@@ -290,9 +295,6 @@ function import_drupal_config() {
   # @see https://www.drupal.org/node/2851877
   drush -q ev '\Drupal::languageManager()->getLanguageConfigOverrideStorage("fr")->delete("system.site");' >/dev/null 2>&1 || true
 
-  # Disabling "automated cron"
-  drush -q config-set automated_cron.settings interval 0 -y >/dev/null 2>&1 || true
-
   # Rebuild cache
   drush cache-rebuild
 }
@@ -395,8 +397,15 @@ if [ "$1" = "bootstrap" ]; then
       drush config-set system.site uuid "$SITE_UUID" -y
     )
 
+    # First attemps to update database (can fail)
+    drush updatedb -y || true
+
     # Load config
     import_drupal_config
+
+    # Final attempt to update database and entities
+    drush updatedb -y
+    drush entity:update -y
 
     # Save database dump after install
     database_dump
